### ISSUE TITLE
Unhandled rejection error caused by redirect

### ISSUE THREAD

**Issue by fcanela** [jdxcode/npm-register#15]
I am excited about your project. Sinopia seems unmaintained and it doesn't seem to be a stable and maintained fork out there. I will test elephant to my pet projects and promote it in my company if it fits our needs.

I cloned the repo, created a S3 bucket (eu-west), AIM credentials, set up the env vars and run the start npm task.

After replying the 3 npm login questions with the registry option pointing to the port 3000:

```
Unhandled rejection Error: Error downloading /htpasswd
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>TemporaryRedirect</Code><Message>Please re-send this request to the specified         temporary endpoint. Continue to use the original request endpoint for future requests.</Message>            <Bucket>HIDDENHIDDEN</Bucket><Endpoint>HIDDENHIDDEN.s3-eu-west-1.amazonaws.com</Endpoint>    <RequestId>A66FD56DF0A7DDD6</RequestId><HostId>Cq8jCPIcjKq2yv20euEdOjbZKparRPx62B/M3Jvy8M6vIaH9Wqf0cl/e+Xo8SF+seXOE8FAvonc=</HostId></Error>
at /home/fcanela/sites/npm.aire/elephant/lib/s3.js:19:19
at tryCatcher (/home/fcanela/sites/npm.aire/elephant/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/fcanela/sites/npm.aire/elephant/node_modules/bluebird/js/release/promise.js:504:31)
at Promise._settlePromise (/home/fcanela/sites/npm.aire/elephant/node_modules/bluebird/js/release/promise.js:561:18)
at Promise._settlePromise0 (/home/fcanela/sites/npm.aire/elephant/node_modules/bluebird/js/release/promise.js:606:10)
at Promise._settlePromises (/home/fcanela/sites/npm.aire/elephant/node_modules/bluebird/js/release/promise.js:685:18)
at Async._drainQueue (/home/fcanela/sites/npm.aire/elephant/node_modules/bluebird/js/release/async.js:138:16)
at Async._drainQueues (/home/fcanela/sites/npm.aire/elephant/node_modules/bluebird/js/release/async.js:148:10)
at Immediate.Async.drainQueues (/home/fcanela/sites/npm.aire/elephant/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:566:20)
at tryOnImmediate (timers.js:546:5)
at processImmediate [as _immediateCallback] (timers.js:525:5)
```

Am I missing something?

**Comment by dickeyxxx** [comment]
it just looks like your keys don't have permission, maybe try seeing if you can use the aws s3 cli client to list, put, and get objects?

**Comment by dickeyxxx** [comment]
I put in the bucket policy for reference that we use: https://github.com/dickeyxxx/elephant/blob/master/s3_bucket_policy.json

**Comment by fcanela** [comment]
I gave it full S3 access but I will check and retry. Thanks.

**Comment by fcanela** [comment]
The credentials has the following policy attached:

    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": "s3:*",
          "Resource": "*"
        }
      ]
    }

**Comment by dgautsch** [comment]
Closing, no activity for over a year.
